name: simacca

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: simacca_app
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/var/www/html
    networks:
      - simacca_network

  webserver:
    image: nginx:alpine
    container_name: simacca_nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8081}:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - simacca_network

networks:
  simacca_network:
    driver: bridge